# CONFIG_SERIAL=y
# CONFIG_CONSOLE=y
# CONFIG_UART_CONSOLE=y

CONFIG_CUSTOM_DISPLAY=y

# Disable PMP features to prevent hardware lockouts
# Add these lines instead to disable PMP features:
CONFIG_HW_STACK_PROTECTION=n
CONFIG_USERSPACE=n
CONFIG_RISCV_PMP=n
# CONFIG_QEMU_FWCFG=n

CONFIG_MAIN_STACK_SIZE=6144
CONFIG_LOG=y
CONFIG_SHELL=y

CONFIG_LVGL=y
CONFIG_LV_Z_MEM_POOL_SIZE=58368
CONFIG_LV_Z_SHELL=y
CONFIG_LV_USE_MONKEY=y

CONFIG_DISPLAY=y
CONFIG_INPUT=y

CONFIG_LV_FONT_MONTSERRAT_12=y
CONFIG_LV_FONT_MONTSERRAT_14=y
CONFIG_LV_FONT_MONTSERRAT_16=y
CONFIG_LV_FONT_MONTSERRAT_18=y
CONFIG_LV_FONT_MONTSERRAT_24=y

# Benchmark Demo
CONFIG_LV_USE_FONT_COMPRESSED=y
CONFIG_LV_Z_DEMO_BENCHMARK=y
CONFIG_LV_Z_DEMO_MUSIC=n
CONFIG_LV_Z_DEMO_WIDGETS=n
CONFIG_LV_Z_DEMO_KEYPAD_AND_ENCODER=n
CONFIG_LV_Z_DEMO_RENDER=n
CONFIG_LV_Z_DEMO_STRESS=n

